"""Add custom_commands + mod_cases tables, and the commands JSON column on guild_settings.

Revision ID: 3322d313cac5
Revises: 956b6a53592c
Create Date: 2026-05-25 15:01:53.338967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3322d313cac5'
down_revision: Union[str, None] = '956b6a53592c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('response_type', sa.String(length=16), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('embed', sa.JSON(), nullable=True),
    sa.Column('allowed_role_ids', sa.JSON(), nullable=False),
    sa.Column('allowed_channel_ids', sa.JSON(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'trigger', name='uq_custom_commands_guild_trigger')
    )
    op.create_index(op.f('ix_custom_commands_guild_id'), 'custom_commands', ['guild_id'], unique=False)
    op.create_table('mod_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.UUID(), nullable=False),
    sa.Column('case_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_username', sa.String(length=64), nullable=False),
    sa.Column('moderator_user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_username', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'case_number', name='uq_mod_cases_guild_case')
    )
    op.create_index(op.f('ix_mod_cases_guild_id'), 'mod_cases', ['guild_id'], unique=False)
    op.create_index(op.f('ix_mod_cases_target_user_id'), 'mod_cases', ['target_user_id'], unique=False)
    op.add_column('guild_settings', sa.Column('commands', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'commands')
    op.drop_index(op.f('ix_mod_cases_target_user_id'), table_name='mod_cases')
    op.drop_index(op.f('ix_mod_cases_guild_id'), table_name='mod_cases')
    op.drop_table('mod_cases')
    op.drop_index(op.f('ix_custom_commands_guild_id'), table_name='custom_commands')
    op.drop_table('custom_commands')
    # ### end Alembic commands ###
